/**
 * Downloads the two web fonts ONCE and keeps them inside the app.
 *
 * Why: the app (installed app and desktop app) must not talk to any third-party
 * server — a study app that works offline should not need fonts.googleapis.com
 * either. Google's CSS is fetched, every woff2 file of the Bangla + Latin
 * subsets is downloaded into `public/fonts/`, and a local `fonts.css` is written
 * with the same unicode-ranges, so the browser still loads only the subsets a
 * page really needs.
 *
 * Run (only when the fonts should be refreshed):
 *   cd client && node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, '..', 'public', 'fonts');
const cssFile = path.join(outDir, 'fonts.css');

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+Bengali:wght@400;500;600;700&display=swap';

// a modern Chrome UA makes Google serve woff2 (smallest, supported everywhere the app runs)
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

fs.mkdirSync(outDir, { recursive: true });

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((response) => {
  if (!response.ok) throw new Error(`Google Fonts CSS failed: ${response.status}`);
  return response.text();
});

// one @font-face per (family, weight, subset) — the subset name sits in a comment above it
const blocks = css.split('/*').slice(1);
const rewritten = [];
let downloaded = 0;
let bytes = 0;

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim();
  const body = block.slice(block.indexOf('*/') + 2);
  const match = body.match(/@font-face\s*{([\s\S]*?)}/);
  if (!match) continue;

  const url = match[1].match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  const name = url.split('/').pop();
  const target = path.join(outDir, name);
  if (!fs.existsSync(target)) {
    const data = await fetch(url, { headers: { 'User-Agent': UA } }).then((response) => response.arrayBuffer());
    fs.writeFileSync(target, Buffer.from(data));
    downloaded += 1;
    bytes += data.byteLength;
  }

  rewritten.push(
    `/* ${subset} */\n@font-face {${match[1].replace(url, `./${name}`).trimEnd()}\n}`
  );
}

const header = `/*
 * Self-hosted web fonts — generated by scripts/fetch-fonts.mjs, do not edit by hand.
 *
 * Inter (Latin) + Noto Sans Bengali, woff2, subset by unicode-range exactly like
 * Google serves them. Keeping them inside the app means the installed app and the
 * desktop app need no internet and contact no third party at all.
 */
`;
fs.writeFileSync(cssFile, `${header}\n${rewritten.join('\n\n')}\n`);

console.log(`[fonts] ${rewritten.length} @font-face rules, ${downloaded} new file(s), ${(bytes / 1024).toFixed(0)} KB downloaded`);
console.log(`[fonts] written to public/fonts/fonts.css`);
