import { useEffect, useMemo, useState } from 'react';
import { Image, Sparkles, Copy, RefreshCw, Pencil, Check, Info } from 'lucide-react';
import { Modal, Button, Badge, Spinner } from '../ui/index.jsx';
import { api } from '../../api/client.js';
import { useToast } from '../../state/ToastContext.jsx';
import { useAppData } from '../../state/AppDataContext.jsx';

/**
 * 🖼️ Create Illustration (Phase 4, first feature)
 *
 * Builds a ready-to-paste image-generation prompt out of the topic's own data.
 * No AI API is called and no API key is needed — the prompt is generated by the
 * app itself (server/src/services/illustration/*) and the student pastes it
 * into ChatGPT / Gemini / any image model.
 *
 * The subject, chapter and topic come from the data the page already has, so
 * nothing has to be typed again (spec §13).
 */
const FALLBACK_TYPES = [
  { value: 'concept_diagram', label: 'Concept Diagram', labelBn: 'Concept Diagram — অংশগুলো কীভাবে সম্পর্কিত' },
  { value: 'process_flow', label: 'Process Flow', labelBn: 'Process Flow — ধাপে ধাপে কী ঘটে' },
  { value: 'architecture_diagram', label: 'Architecture Diagram', labelBn: 'Architecture Diagram — স্তর ও ব্লক' },
  { value: 'educational_illustration', label: 'Educational Illustration', labelBn: 'Educational Illustration — সহজ করে বোঝানো ছবি' },
  { value: 'concept_visualization', label: 'Concept Visualization', labelBn: 'Concept Visualization — কঠিন ভাবনাকে ছবিতে' },
];

export default function CreateIllustrationModal({ open, onClose, topic, chapter, subject }) {
  const toast = useToast();
  const { meta } = useAppData();

  const types = meta?.illustrationTypes?.length ? meta.illustrationTypes : FALLBACK_TYPES;

  const [type, setType] = useState('educational_illustration');
  const [result, setResult] = useState(null);
  const [prompt, setPrompt] = useState('');
  const [editing, setEditing] = useState(false);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);

  // a fresh modal starts clean, with the spec's default type selected
  useEffect(() => {
    if (!open) return;
    setResult(null);
    setPrompt('');
    setEditing(false);
    setCopied(false);
    setType('educational_illustration');
  }, [open, topic?.id]);

  const generate = async (variant = 0, nextType = type) => {
    if (!topic?.id) return;
    setBusy(true);
    try {
      const data = await api.topics.illustrationPrompt(topic.id, { type: nextType, variant });
      setResult(data);
      setPrompt(data.prompt);
      setType(data.type);
      setEditing(false);
      setCopied(false);
    } catch (error) {
      toast.error(error.message);
    } finally {
      setBusy(false);
    }
  };

  /** 🔄 Regenerate: next variant of this type, then the next illustration type. */
  const regenerate = () => {
    if (!result) return generate(0);
    const nextVariant = result.variant + 1;
    if (nextVariant < result.variantCount) return generate(nextVariant, result.type);
    return generate(0, result.nextType);
  };

  const copyPrompt = async () => {
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(prompt);
      } else {
        // fallback for browsers (or embedded views) without the clipboard API
        const area = document.createElement('textarea');
        area.value = prompt;
        document.body.appendChild(area);
        area.select();
        document.execCommand('copy');
        document.body.removeChild(area);
      }
      setCopied(true);
      toast.success('Prompt copied successfully!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      toast.error('Copy করা গেল না — পুরো লেখাটা select করে নিজে copy করো');
    }
  };

  const typeLabel = useMemo(() => types.find((entry) => entry.value === type)?.label ?? type, [types, type]);
  const nextTypeLabel = useMemo(
    () => types.find((entry) => entry.value === result?.nextType)?.label ?? result?.nextType,
    [types, result]
  );

  const regenerateLabel = !result
    ? 'Regenerate'
    : result.variant + 1 < result.variantCount
      ? `${typeLabel} variant ${result.variant + 2}/${result.variantCount}`
      : `পরের type: ${nextTypeLabel ?? ''}`;

  return (
    <Modal
      open={open}
      title="Create Educational Illustration"
      onClose={onClose}
      size="lg"
      footer={
        <>
          <Button variant="ghost" onClick={onClose}>
            বন্ধ করো
          </Button>
          {result && (
            <Button variant="ghost" onClick={regenerate} disabled={busy}>
              <RefreshCw className="mr-1.5 h-4 w-4" />
              Regenerate
            </Button>
          )}
          {result && (
            <Button onClick={copyPrompt} disabled={busy}>
              {copied ? <Check className="mr-1.5 h-4 w-4" /> : <Copy className="mr-1.5 h-4 w-4" />}
              {copied ? 'Copied!' : 'Copy Prompt'}
            </Button>
          )}
        </>
      }
    >
      <div className="space-y-4">
        {/* where this prompt comes from — filled in automatically */}
        <div className="rounded-2xl border border-ink-200 bg-ink-50/70 p-3">
          <p className="muted">Subject</p>
          <p className="text-sm font-medium text-ink-900">{subject?.name ?? '—'}</p>
          <p className="muted mt-1.5">Chapter</p>
          <p className="text-sm font-medium text-ink-900">
            {chapter ? `Chapter ${chapter.number} — ${chapter.name}` : '—'}
          </p>
          <p className="muted mt-1.5">Topic</p>
          <p className="text-sm font-medium text-ink-900">{topic?.name ?? '—'}</p>
        </div>

        <div>
          <label className="label">Illustration type</label>
          <div className="grid gap-2 sm:grid-cols-2">
            {types.map((entry) => (
              <button
                key={entry.value}
                type="button"
                onClick={() => {
                  setType(entry.value);
                  if (result) generate(0, entry.value);
                }}
                className={`rounded-xl border px-3 py-2 text-left text-sm transition-colors ${
                  type === entry.value ? 'border-brand-300 bg-brand-50 text-brand-800' : 'border-ink-200 bg-white text-ink-700 hover:bg-ink-50'
                }`}
              >
                <span className="font-medium">{entry.label}</span>
                <span className="muted block">{entry.labelBn}</span>
              </button>
            ))}
          </div>
        </div>

        {!result && (
          <Button onClick={() => generate(0, type)} disabled={busy || !topic?.id}>
            <Sparkles className="mr-1.5 h-4 w-4" />
            {busy ? 'তৈরি হচ্ছে...' : 'Generate Prompt'}
          </Button>
        )}

        {busy && !result && <Spinner label="Prompt তৈরি হচ্ছে..." />}

        {result && (
          <div className="space-y-2">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="flex flex-wrap items-center gap-2">
                <Badge className="border-brand-200 bg-brand-50 text-brand-700">{result.typeLabel}</Badge>
                <Badge>
                  variant {result.variant + 1}/{result.variantCount}
                </Badge>
                <Badge>
                  {result.profile.components.length} টা অংশ · {result.profile.flow.length} ধাপ
                </Badge>
              </div>
              <button type="button" className="btn-ghost" onClick={() => setEditing((value) => !value)}>
                <Pencil className="h-4 w-4" />
                {editing ? 'Edit বন্ধ করো' : '✏️ Edit Prompt'}
              </button>
            </div>

            {editing ? (
              <textarea
                className="input min-h-72 resize-y font-mono text-xs leading-relaxed"
                value={prompt}
                onChange={(event) => setPrompt(event.target.value)}
              />
            ) : (
              <pre className="max-h-72 overflow-auto whitespace-pre-wrap rounded-xl border border-ink-200 bg-ink-50/60 p-3 font-mono text-xs leading-relaxed text-ink-800">
                {prompt}
              </pre>
            )}
            <p className="muted">
              {editing
                ? 'টাইপ করে বদলাতে পারো — বদলানোর পর Copy Prompt চাপলেই এই লেখাটাই copy হবে।'
                : 'Edit চাপলে এই prompt নিজে বদলাতে পারবে।'}
            </p>

            <div className="flex flex-wrap gap-2">
              <Button onClick={copyPrompt}>
                {copied ? <Check className="mr-1.5 h-4 w-4" /> : <Copy className="mr-1.5 h-4 w-4" />}
                {copied ? 'Prompt copied successfully!' : '📋 Copy Prompt'}
              </Button>
              <Button variant="ghost" onClick={regenerate} disabled={busy}>
                <RefreshCw className="mr-1.5 h-4 w-4" />
                🔄 {regenerateLabel}
              </Button>
            </div>

            <p className="flex items-start gap-2 rounded-xl border border-ink-200 bg-white p-3 text-xs text-ink-600">
              <Info className="mt-0.5 h-4 w-4 shrink-0 text-ink-400" />
              <span>
                এই prompt copy করে ChatGPT / Gemini বা যেকোনো image-generating AI-তে paste করো। ছবি হয়ে গেলে সেটা
                নিজে Study Hub-এ save করে রাখো (AI image সংরক্ষণ Phase 5-এ আসবে)। কোনো AI API বা API key লাগে না —
                prompt সম্পূর্ণভাবে তোমার নিজের topic data থেকে তৈরি।
              </span>
            </p>
          </div>
        )}

        {!result && (
          <p className="flex items-start gap-2 text-xs text-ink-500">
            <Image className="mt-0.5 h-4 w-4 shrink-0 text-ink-400" />
            <span>
              Subject, Chapter আর Topic উপর থেকে নিজে থেকেই নেওয়া হয়েছে — আবার লিখতে হবে না। Generate Prompt চাপলে
              topic-এর অংশ, ধাপ আর সম্পর্ক সহ একটি পূর্ণ prompt তৈরি হবে।
            </span>
          </p>
        )}
      </div>
    </Modal>
  );
}
