import { Router } from 'express';
import {
  contentKinds,
  generateForTopic,
  saveFromRequest,
  listByTopic,
  listAll,
  updateContent,
  deleteContent,
  saveAsNote,
  contentStats,
} from '../services/studyContentService.js';
import { asyncHandler, toInt } from '../utils/http.js';

/**
 * Study content (Phase 4) — generated by pattern + hand-written Bangla knowledge.
 * No AI API is called anywhere in this router.
 *
 *   GET    /api/study-content                     all saved content + kinds + stats
 *   GET    /api/study-content/stats               how much has been generated
 *   GET    /api/study-content/kinds               the nine sections + honesty note
 *   GET    /api/study-content/topic/:topicId      what is saved for one topic
 *   POST   /api/study-content/topic/:topicId/generate   build (optionally save)
 *   POST   /api/study-content/topic/:topicId/save       save generated sections
 *   PATCH  /api/study-content/:id                 edit a saved section
 *   DELETE /api/study-content/:id                 delete a saved section
 *   POST   /api/study-content/:id/to-note         copy it into AI notes (source=ai)
 */
export function studyContentRouter({ getUserId }) {
  const router = Router();

  router.get(
    '/',
    asyncHandler(async (req, res) => {
      res.json({ ...listAll(getUserId(req), req.query.limit), stats: contentStats(getUserId(req)) });
    })
  );

  router.get(
    '/stats',
    asyncHandler(async (req, res) => {
      res.json(contentStats(getUserId(req)));
    })
  );

  router.get(
    '/kinds',
    asyncHandler(async (_req, res) => {
      res.json(contentKinds());
    })
  );

  router.get(
    '/topic/:topicId',
    asyncHandler(async (req, res) => {
      res.json(listByTopic(getUserId(req), toInt(req.params.topicId, 'topicId')));
    })
  );

  router.post(
    '/topic/:topicId/generate',
    asyncHandler(async (req, res) => {
      res.json(
        generateForTopic(getUserId(req), toInt(req.params.topicId, 'topicId'), {
          kinds: Array.isArray(req.body?.kinds) ? req.body.kinds : undefined,
          save: Boolean(req.body?.save),
        })
      );
    })
  );

  router.post(
    '/topic/:topicId/save',
    asyncHandler(async (req, res) => {
      res.json(saveFromRequest(getUserId(req), toInt(req.params.topicId, 'topicId'), req.body ?? {}));
    })
  );

  router.patch(
    '/:id',
    asyncHandler(async (req, res) => {
      res.json(updateContent(getUserId(req), toInt(req.params.id, 'id'), req.body ?? {}));
    })
  );

  router.delete(
    '/:id',
    asyncHandler(async (req, res) => {
      deleteContent(getUserId(req), toInt(req.params.id, 'id'));
      res.status(204).end();
    })
  );

  router.post(
    '/:id/to-note',
    asyncHandler(async (req, res) => {
      res.status(201).json(saveAsNote(getUserId(req), toInt(req.params.id, 'id')));
    })
  );

  return router;
}
